# Generated by Django 3.0.8 on 2020-07-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('time_starts', models.DateField()),
                ('time_ends', models.DateField()),
                ('label', models.CharField(choices=[('t', 'Top'), ('m', 'Medium'), ('l', 'Low')], default='m', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
